# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: src/CustomerApi/Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CUSTOMER_DB_CONNECTION_STRING}
    depends_on:
      - mydb
  mydb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  userauthapi:
    image: userauthapi
    build: 
      context: .
      dockerfile: src/UserAuthApi/Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5028:5028"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthDatabase=${AUTH_DB_CONNECTION_STRING}
    depends_on:
      - userdb

  userdb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: UserDB-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${AUTH_DB_SA_PASSWORD}
